hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/Obeb.o -c ./src/Obeb.cpp
	g++ -I ./include/ -o ./lib/Mod.o -c ./src/Mod.cpp
	g++ -I ./include/ -o ./bin/odev ./lib/Obeb.o ./lib/Mod.o ./src/odev.cpp
	
calistir:
	./bin/odev